#!/usr/bin/python3

class Square():
    
    def __init__(self, side_length=0):
        self.side_length = side_length
    
    def area(self):
        """ Area of the square """
        return self.side_length ** 2

    def perimeter(self):
        """ Perimeter of the square """
        return self.side_length * 4

    def __str__(self):
        """ String representation of the square """
        return str(self.side_length)

if __name__ == "__main__":
    s = Square(side_length=12)
    print(s)
    print(s.area())
    print(s.perimeter())

